version: '3.8'  

services:
  iac_website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:80"
      - "7071:80"
    hostname: iac_website
    container_name: iac_website
    volumes:
      - iac_db_data:/var/www/html 

volumes:
  iac_db_data:

